-- Run once in Snowflake.
-- The warehouse automatically suspends after 60 seconds.

CREATE WAREHOUSE IF NOT EXISTS CHURN_WH
    WITH WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE;

CREATE DATABASE IF NOT EXISTS CHURN_DB;

CREATE SCHEMA IF NOT EXISTS CHURN_DB.RAW;
CREATE SCHEMA IF NOT EXISTS CHURN_DB.ANALYTICS;

USE WAREHOUSE CHURN_WH;
USE DATABASE CHURN_DB;

CREATE OR REPLACE FILE FORMAT CHURN_DB.RAW.TELCO_CSV_FORMAT
    TYPE = CSV
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
    SKIP_HEADER = 1
    NULL_IF = ('', 'NULL');

CREATE STAGE IF NOT EXISTS CHURN_DB.RAW.TELCO_STAGE
    FILE_FORMAT = CHURN_DB.RAW.TELCO_CSV_FORMAT;